// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhOYc1EQ3a3kh92f-M_PneBnvFZJAXAtM',
    appId: '1:695787289329:web:ca9051968a41ac869c8750',
    messagingSenderId: '695787289329',
    projectId: 'js-test-e5720',
    authDomain: 'js-test-e5720.firebaseapp.com',
    databaseURL: 'https://js-test-e5720.firebaseio.com',
    storageBucket: 'js-test-e5720.appspot.com',
    measurementId: 'G-LKHRJPEZT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaiy0SmZPP4fxprzfBj818OwRfwI6lcSA',
    appId: '1:695787289329:android:89c2d8c44b6d6fee9c8750',
    messagingSenderId: '695787289329',
    projectId: 'js-test-e5720',
    databaseURL: 'https://js-test-e5720.firebaseio.com',
    storageBucket: 'js-test-e5720.appspot.com',
  );
}
